### ISSUE TITLE
Question: Nats Resolver

### ISSUE THREAD

**Issue by aKardasz** [edgefarm/vault-plugin-secrets-nats#18]
Does the plugin support pushing to the nats resolver? If I am not mistaken it should function pretty similar to the account based one that is a seperate repo.

**Comment by siredmar** [comment]
The plugin does support pushing to a NATS resolver. 
Just configure the operator with the `syncAccountServer` flag and put in a `accountServerUrl` in the operator.
See this example: https://github.com/edgefarm/vault-plugin-secrets-nats/blob/main/example/operator/operator.json

I don't understand what you mean by `the account based one that is a seperate repo`. Would you explain?

**Comment by siredmar** [comment]
btw, if you are using Kubernetes, try out our crossplane provider for this vault plugin as it makes things much easier.

**Comment by aKardasz** [comment]
You answered my question, what I meant by second repo is the nats-account-server repo that is deprecated now.
